### ISSUE TITLE
m-textarea : Descenders not visible

### ISSUE THREAD

**Issue by frbro43** [ulaval/modul-components#124]
The descenders, the part of a character (g, j, p, q, y) that descends below the baseline, are not visible in the text area.

![2018-03-06_1058](https://user-images.githubusercontent.com/36742654/37044092-9020be78-2130-11e8-936e-8e3b8b5dcbb8.png)

**Comment by setur52** [comment]
The problem seems to be solved, is it still on your side?

**Comment by jipigi** [comment]
Le problème persiste, mais est reproductible uniquement dans Prisme, Raphaël a essayé un nouveau correctif après avoir fait des tests plus poussés vendredi passé. Il faudrait l'inclure dans la prochaine release pour qu'un analyste puisse tester le tout dans Prisme. Merci !

**Comment by simardo** [comment]
Devrait être fixé dans la 26  https://github.com/ulaval/modul-components/issues?q=is%3Aclosed+milestone%3A1.0.0-beta.26

**Comment by simardo** [comment]
Je considère le problème réglé. Si c'est encore présent, SVP ouvrir un billet MODUL.

**Comment by jipigi** [comment]
Je confirme le correctif a bien été intégré et testé dans Prisme, tout fonctionne bien :
Voir https://jira.dti.ulaval.ca/browse/ENA2-599
Merci.
