### ISSUE TITLE
m-tooltip : Property to see the tooltip by default

### ISSUE THREAD

**Issue by frbro43** [ulaval/modul-components#125]
We would like to have a property which allow us to have the tooltip open by default.

![2018-03-06_1135](https://user-images.githubusercontent.com/36742654/37044844-8c127c52-2132-11e8-93a8-22792ad9dddd.png)

**Comment by frbro43** [comment]
I dont know where to pull my request, sorry.

**Comment by frbro43** [comment]
My ticket doesn't want to stay open.

**Comment by setur52** [comment]
The problem is fixed and will be corrected in the next version of modul
Pull request #142
