### ISSUE TITLE
Add named route support to m-link component

### ISSUE THREAD

**Issue by yohanndumais** [ulaval/modul-components#14]
I would be nice for the m-link component to support named routes.

Exemple from vue router-link:
```
<!-- named route -->
<router-link :to="{ name: 'user', params: { userId: 123 }}">User</router-link>
```

[https://router.vuejs.org/en/api/router-link.html](url)

**Comment by yohanndumais** [comment]
Originalement, j'ai mentionné named route mais idéalement, la solution serait de supporter un router-link comme destination (enfin, je crois).

**Comment by simardo** [comment]
Usage (mode="router-link" - default)

`<m-link url="/test"></m-link>` equals `<m-link url="{path: '/test'}">my test</m-link>`
so this will be valid:
`<m-link url="{ name: 'user', params: { userId: 123 }}">user</m-link>`

Available in the next release.
