### ISSUE TITLE
v-m-i18n placeholder

### ISSUE THREAD

**Issue by gabra20** [ulaval/modul-components#218]
- [x ] Provide a description of the issue
La directive v-m-i18n avec attribut placeholder ne place pas l'attribut au bon endroit avec m-textfield ou m-textarea
- [x ] Provide the expected behaviour
Le placeholder devrait se mettre sur l'input/textarea a l'intérieur de la div du component

**Comment by simardo** [comment]
Puisque tu as déjà un billlet dans Jira pour ça, pas besoin d'ouvrir un issue dans github.

**Comment by gabra20** [comment]
ah ok, je viens de voir la petite étoile dans le CONTRIBUTING. Sorry!
