### ISSUE TITLE
MAccordionGroup crashes when programmatically removing children

### ISSUE THREAD

**Issue by Gehbrial** [ulaval/modul-components#290]
## `@ulaval/modul-components`
# Issue Checklist

- [x ] Provide a description of the issue
Lorsque les enfants (MAccordion) d'un composant MAccordionGroup ont un rendu conditionnel, celui-ci lance une exception lorsqu'un des enfants qui, auparavant était affiché, ne l'est plus.

```
TypeError: Cannot read property 'propOpen' of undefined
    at VueComponent.get (accordion-group.js?2ca6:52)
    at Watcher.get (vue.esm.js?a026:3142)
    at Watcher.evaluate (vue.esm.js?a026:3249)
    at Proxy.computedGetter (vue.esm.js?a026:3507)
    at Proxy.render (accordion-group.html?11af:1)
    at VueComponent.Vue._render (vue.esm.js?a026:4544)
    at VueComponent.updateComponent (vue.esm.js?a026:2788)
    at Watcher.get (vue.esm.js?a026:3142)
    at Watcher.run (vue.esm.js?a026:3219)
    at flushSchedulerQueue (vue.esm.js?a026:2981)
```

If submitting a bug
- [x ] Provide a step by step way to reproduce the problem with screenshot or video

component.html
```
<m-accordion-group>
    <m-accordion v-for="item in items">
        <span>{{ item }}</span>
    </m-accordion>
</m-accordion-group>
```

component.ts
```
items: Array<string> = ["Foo", "Bar"]

removeItem() {
    this.items.pop();
}
```

- [ x] Provide the expected behaviour
On devrait pouvoir ajouter et enlever des accordéons de la liste de façon dynamique. Il serait également bien si on gardait en mémoire l'état de l'accordéon (ouvert ou fermé) à sa réintroduction dans la liste. À noter qu'on peut gérer ce comportement sans utiliser ce composant. On peut donc remettre sa nécessité en question.
- [x ] I'm not an internal contributor

**Comment by setur52** [comment]
@lucmartin3elien  ce n'est pas le problème que tu as réglé?

**Comment by lucmartin3elien** [comment]
Ce problème a été corrigé dans un un billet (MODUL-941).
