### ISSUE TITLE
MAccordion's 'open' prop should override 'internalPropOpen' property

### ISSUE THREAD

**Issue by Gehbrial** [ulaval/modul-components#296]
## `@ulaval/modul-components`
# Issue Checklist

- [x ] Provide a description of the issue
Lorsqu'on fournit une valeur booléenne à la prop _open_ du component MAccordion, l'ouverture ou la fermeture du component ne devrait déprendre que de cette valeur.

- [x ] Provide a step by step way to reproduce the problem with screenshot or video
1. Passez la valeur "false" à la prop _open_
2. Clickez sur l'accordéon

L'accordéon s'ouvre tout de même alors qu'il ne devrait pas.

- [x ] Provide the expected behaviour
L'accordéon ne devrait pas s'ouvrir.

- [x ] I'm not an internal contributor

**Comment by chuckmah** [comment]
open.sync
