### ISSUE TITLE
Problem with m-icon used within m-step

### ISSUE THREAD

**Issue by simardo** [ulaval/modul-components#4]
Looks like the binary is used instead of the resource itself:

![image](https://user-images.githubusercontent.com/1334127/27227526-cc4f78dc-5271-11e7-976d-c41aed8fd156.png)

ref: P408-34, P408-7

**Comment by yohanndumais** [comment]
Added this configuration in my project to fix the issue 
```
#../conf/webpack.config.js
...
                {
                    test: /\.svg$/,
                    loader: 'svg-inline-loader',
                    options: {
                        removeTags: true,
                        removingTags: ['desc', 'defs', 'style'],
                        removeSVGTagAttrs: true
                    }
                },
...
```

**Comment by simardo** [comment]
Fixed in base template. [commit here](https://github.com/ulaval/modul-typescript-template/commit/b63dd666b7a7478ac27f3536daa694a8d3b016a9)
