### ISSUE TITLE
m-menu-item and m-sidebar: stack problem

### ISSUE THREAD

**Issue by LindaDelaney** [ulaval/modul-components#48]
When m-menu-item is used to open m-sidebar, a sidebar is added in Modul.prototype.pushElement stack (line 72) but is immediatly popped in Modul.prototype.popElement (line 78), resulting in the menu being the only element left in the stack. The opposite should occur.

P408-122

**Comment by simardo** [comment]
Waiting for steps to reproduce... P408-122 assigned to reporter.
