### ISSUE TITLE
L'installation en tant que dépendance ne fonctionne pas

### ISSUE THREAD

**Issue by Gehbrial** [ulaval/modul-components#531]
Lors de l'ajout de la librairie en tant que dépendance externe dans un projet, le processus usuel d'installation ne fonctionne pas. En effet nous serions supposés pouvoir:

`npm install --save @ulaval/modul-components`

 Dans le fichier d'entrée, de l'application: 
`import Modul from "@ulaval/modul-component";`
`import "@ulaval/modul-component/style.min.css";`
`Vue.use(Modul)`

Par la suite, les composants seraient exposés dans l'application. Nous serions également supposés pouvoir importer les composants au besoin plutôt que d'installer la librairie globalement.

Il est cependant impossible de procéder de cette façon puisque:
1. ` import Modul from "@ulaval/modul-component"` retourne _undefined_ alors que Modul devrait être un objet exposant une fonction _install_
2. Le dossier de la librairie ne possède pas une version minifée du style. En d'autres mots, `@ulaval/modul-component/style.min.css` n'existe pas.

La seule façon de faire fonctionner la librairie est en incluant les loaders appropriés dans la configuration webpack de l'application développée. En procédant de cette façon, on rencontre plusieurs problèmes:

1. Il est impossible d'utiliser la librairie dans une application qui utilise des _single-file-components_ (la façon la plus commune de développer en Vue). En effet, il est impossible de faire cohabiter _vue-loader_ et _vue-template-loader_ dans un même processus de build. 

2. L'installation de la librairie ne respecte pas la façon usuelle de faire (celle décrite plus haut). En effet, on doit plutôt: `import Modul from "@ulaval/modul-components/dist/components"; Modul.install(Vue);`

3. Il est impossible de choisir les composants à utiliser. En effet, seule une installation globale fonctionne. Cela force également l'installation globale de tous les icônes puisque plusieurs composants les utilisent. Si les icône ne sont pas importés globalement mais que les composants le sont, les composants qui les utilisent ne les affichent pas et on obtient des warnings dans la console.

4. On force l'utilisation de SASS. En effet, il est obligatoire d'importer `"@ulaval/modul-components/dist/styles/main.scss"` dans le fichier d'entrée de l'application pour que l'ensemble des styles de la librairie se chargent correctement.

Somme toute, il est quasi impossible d'utiliser la librairie en tant que dépendance sans faire d'importants compromis et sans procéder d'une manière non documentée qui est source de nombreux problèmes.

**Comment by chuckmah** [comment]
Salut @Gehbrial  , je vais m'occupé de modul-components en remplacement de @vidal7 

Pour ce qui est des changements que tu proposes il va être très difficile de les faire sans gros changements structurels majeurs. Peut-être faire dans une version 2. 

En attendant la version 1 officiel (on est encore en Beta) j'ai fait plusieurs fixes pour améliorer l'utilisation de modul en tant que librairie. (https://github.com/ulaval/modul-components/pull/478)  (https://github.com/ulaval/modul-components/pull/553)  (https://github.com/ulaval/modul-components/pull/471) 

Pour ce qui est des problèmes:

> Il est impossible d'utiliser la librairie dans une application qui utilise des single-file-components (la façon la plus commune de développer en Vue). En effet, il est impossible de faire cohabiter vue-loader et vue-template-loader dans un même processus de build.

Oui c'est possible d'utiliser les single file components mais on suggère fortement de structuré le code des applications de la même façon que module. Comme référence tu peux utiliser https://github.com/simardo/vuejs-typescript-template  (c'est a dire en typescript, avec des templates externes et l'utilisation de scss).
J'ai fait un test avec le vue cli et les single file component tu peux voir le setup ici https://github.com/chuckmah/my-cli-module-project . Tu peux voir les ajouts a la configuration ici (https://github.com/chuckmah/my-cli-module-project/commit/145a4a4cde3684088ea1bfdcc454bcd6e40eaef3) . J'ai pas testé avec tous les components, mais ca semble fonctionner avec les component et les icons.

> L'installation de la librairie ne respecte pas la façon usuelle de faire (celle décrite plus haut). En effet, on doit plutôt: import Modul from "@ulaval/modul-components/dist/components"; Modul.install(Vue);

Comme j'ai dit plus haut ça va être compliqué sans changement majeur mais tu peux voir ce PR (https://github.com/ulaval/modul-components/pull/478) facilite les imports.

> Il est impossible de choisir les composants à utiliser. En effet, seule une installation globale fonctionne. Cela force également l'installation globale de tous les icônes puisque plusieurs composants les utilisent. Si les icône ne sont pas importés globalement mais que les composants le sont, les composants qui les utilisent ne les affichent pas et on obtient des warnings dans la console.

Effectivement modul-components est un gros pain pour l'instant. Impossible d'importer les composantes indépendamment.

> On force l'utilisation de SASS. En effet, il est obligatoire d'importer "@ulaval/modul-components/dist/styles/main.scss" dans le fichier d'entrée de l'application pour que l'ensemble des styles de la librairie se chargent correctement.

Comme dit plus haut l'utilisation de sass est obligatoire, les composantes et les variables doivent être partagé et scopé.

N'hésite pas si tu as d'autre questions!
Charles

**Comment by Gehbrial** [comment]
Merci pour la réponse détaillée. Content de savoir qu'il est possible d'utiliser la librairie dans un flow de développement un peu plus standard. Bien que les quelques compromis à faire sont raisonnables, je crois que la quasi-absence de documentation officielle rend son adoption bien difficile. Bref, je vous souhaite bonne chance dans votre démarche et aie bien hâte de voir les développements futurs du projet!
