### ISSUE TITLE
using m-icon with my own icons

### ISSUE THREAD

**Issue by gbramardi** [ulaval/modul-components#654]
- [ x] Provide a description of the issue
Hi guys, I'd like to use the m-icon component with my own icons, but I can't find a way to do it...
On the doc, there's a link to explain how to do it but it redirects to a 404 page...

I'm able to add a sprite using SpriteService, but it doesn't return the created id so I could use it in the m-icon component...

I could create a MR with addSprite returning the id if you think it's a good way to use it. Otherwise, could you explain to me what I should do?

**Comment by gbramardi** [comment]
Link in the doc:
![capture d ecran de 2019-01-15 10-40-05](https://user-images.githubusercontent.com/46708476/51172172-f67ad080-18b2-11e9-9224-9f5f468a5e7d.png)

404 page:
![capture d ecran de 2019-01-15 10-40-16](https://user-images.githubusercontent.com/46708476/51172175-f67ad080-18b2-11e9-8b5c-1984898f0186.png)

**Comment by chuckmah** [comment]
Salut,

Tu peux faire un PR pour que SpritesService retourne un id. 

On a des éléments dans notre backlog pour changer le fonctionnement des icons qui ne seront plus directement dans le html mais plutôt utilisé a la demande par les projets.
Malheureusement je ne peux pas te donner une date sur la réalisation.

Charles
