### ISSUE TITLE
m-textarea alignment issues

### ISSUE THREAD

**Issue by frbro43** [ulaval/modul-components#90]
Guys are using the text area in Prisme and there are alignment issues. 

For example, on this [page](http://ena2-ui-dev-ena2-exemple.paas.exp.ulaval.ca/a1/modules), use the Designer View and click the Add Module link at the bottom of the page. The "Description" field is not aligned. 

In addition, when you use the text area in a form with data already pre-populated ([here](http://ena2-ui-dev-ena2-exemple.paas.exp.ulaval.ca/a1/modules/a1-a10)), you do not see the text in the area until you click in the form field, and sometimes you also need to start typing on your keyboard.

**Comment by Atiomi** [comment]
Hello @frbro43, this issues should be fix by this #82 commit. 
If so, the fix will be include in the next release.
